"""aaa

Revision ID: 5c511f9e6aa1
Revises: 
Create Date: 2019-05-21 14:54:24.198500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c511f9e6aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_index(op.f('ix_author_surname'), 'author', ['surname'], unique=False)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_name'), 'book', ['name'], unique=False)
    op.create_index(op.f('ix_book_price'), 'book', ['price'], unique=False)
    op.create_index(op.f('ix_book_year'), 'book', ['year'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=False)
    op.create_table('order_from_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CustomerId', sa.Integer(), nullable=True),
    sa.Column('EmployeeId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_to_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ProviderId', sa.Integer(), nullable=True),
    sa.Column('EmployeeId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('adress', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_adress'), 'provider', ['adress'], unique=False)
    op.create_index(op.f('ix_provider_name'), 'provider', ['name'], unique=False)
    op.create_index(op.f('ix_provider_phone'), 'provider', ['phone'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('isEmployee', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_provider_phone'), table_name='provider')
    op.drop_index(op.f('ix_provider_name'), table_name='provider')
    op.drop_index(op.f('ix_provider_adress'), table_name='provider')
    op.drop_table('provider')
    op.drop_table('order_to_provider')
    op.drop_table('order_from_customer')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_book_year'), table_name='book')
    op.drop_index(op.f('ix_book_price'), table_name='book')
    op.drop_index(op.f('ix_book_name'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_author_surname'), table_name='author')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
