"""empty message

Revision ID: 5d95d934bd8c
Revises: 9fca3a257577
Create Date: 2019-05-21 18:04:09.916839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d95d934bd8c'
down_revision = '9fca3a257577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_genre', type_='foreignkey')
    op.create_foreign_key(None, 'book_genre', 'genres', ['GenreId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_genre', type_='foreignkey')
    op.create_foreign_key(None, 'book_genre', 'authors', ['GenreId'], ['id'])
    # ### end Alembic commands ###
