"""empty message

Revision ID: 73500d50ff66
Revises: 190f8e6d6b0c
Create Date: 2019-05-21 20:10:42.799110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73500d50ff66'
down_revision = '190f8e6d6b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_phone', table_name='user')
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.create_index('ix_user_phone', 'user', ['phone'], unique=1)
    # ### end Alembic commands ###
