"""empty message

Revision ID: 97d689551480
Revises: 73500d50ff66
Create Date: 2019-05-22 16:56:24.264373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d689551480'
down_revision = '73500d50ff66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('address', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_provider_address'), 'provider', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('adress', sa.VARCHAR(length=100), nullable=True))
    op.create_index('ix_provider_adress', 'provider', ['adress'], unique=False)
    op.drop_index(op.f('ix_provider_address'), table_name='provider')
    op.drop_column('provider', 'address')
    # ### end Alembic commands ###
