"""empty message

Revision ID: 9fca3a257577
Revises: c52ff3a18401
Create Date: 2019-05-21 16:36:34.080044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fca3a257577'
down_revision = 'c52ff3a18401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BookId', sa.Integer(), nullable=True),
    sa.Column('numberOfBooks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BookId'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('BookId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    # ### end Alembic commands ###
